services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - VITE_API_URL=http://localhost:3001/api
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
        volumes:
            - ./backend/src:/app/src
            - ./backend/package.json:/app/package.json
            - ./backend/package-lock.json:/app/package-lock.json
            - ./backend/tsconfig.json:/app/tsconfig.json
            - /app/node_modules
            - /app/dist
        environment:
            - MONGODB_URI=mongodb://mongodb:27017/attendance
            - REDIS_URL=redis://redis:6379
            - JWT_SECRET=your_jwt_secret_here
            - FRONTEND_URL=http://localhost:3000
        depends_on:
            - mongodb
            - redis

    mongodb:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data:/data/db

    redis:
        image: redis:alpine
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data

volumes:
    mongodb_data:
    redis_data:
